
["WorldProtector mod server configuration"]
	#Default OP level to use WorldProtector commands.
	#Range: 1 ~ 4
	command_op_level = 4
	#Default command alternative used in quick commands in chat.
	#This is only important if another mod uses the /wp command (like Journey Map). Defaults to 0.
	# 0 -> /wp
	# 1 -> /w-p
	# 2 -> /worldprotector
	#Range: 0 ~ 2
	wp_command_alt = 0
	#Default region priority for newly created regions.
	#Range: > 0
	default_region_priority = 2
	#Default region priority increment for usage in commands.
	#Range: 1 ~ 100
	default_region_priority_inc = 1

